/*   Automatically generated by Iup 3 LED Compiler to C.   */

#include <stdlib.h>
#include <stdarg.h>
#include <iup.h>

static Ihandle* named[     13 ];

#include <iupcontrols.h>

void led_load (void)
{
  named[0] = IupSetAtt( "mnu", IupMenu(
    IupSubmenu( "File",
      IupMenu(
        IupSetAtt( NULL, IupItem( "Open file...", "myaction" ), 
          "ACTIVE", "NO", NULL ),
        IupSeparator(),
        IupSetAtt( NULL, IupItem( "Exit", "myaction" ), 
          "ACTIVE", "YES", NULL ),
      NULL)
    ),
  NULL), NULL );
  named[1] = IupSetAtt( "progress", IupGauge(), 
    "VALUE", "0.34", 
    "EXPAND", "horizontal", NULL );
  named[2] = IupSetAtt( "comm_type", IupList( "myaction" ), 
    "DROPDOWN", "YES", 
    "EXPAND", "YES", 
    "VALUE", "1", 
    "1", "Optical", 
    "2", "RS485", NULL );
  named[3] = IupSetAtt( "comm_port", IupList( "myaction" ), 
    "DROPDOWN", "YES", 
    "EXPAND", "YES", 
    "EDITBOX", "YES", NULL );
  named[4] = IupSetAtt( "phy_address", IupText( "myaction" ), 
    "SIZE", "40x", 
    "VALUE", "16", NULL );
  named[5] = IupSetAtt( "user", IupList( "myaction" ), 
    "DROPDOWN", "YES", 
    "EXPAND", "YES", 
    "VALUE", "4", 
    "1", "1", 
    "2", "2", 
    "3", "3", 
    "4", "4", 
    "5", "16", NULL );
  named[6] = IupSetAtt( "auth", IupList( "myaction" ), 
    "DROPDOWN", "YES", 
    "EXPAND", "YES", 
    "VALUE", "2", 
    "1", "No", 
    "2", "LLS", NULL );
  named[7] = IupSetAtt( "password", IupText( "myaction" ), 
    "SIZE", "100x", 
    "VALUE", "", NULL );
  named[8] = IupSetAtt( "highspeed", IupToggle( "RS485 high speed", "myaction" ), 
    "VALUE", "OFF", NULL );
  named[9] = IupSetAtt( "button_start", IupButton( "Start", "myaction" ), 
    "SIZE", "60x", NULL );
  named[10] = IupSetAtt( "button_exit", IupButton( "Exit", "myaction" ), 
    "SIZE", "60x", NULL );
  named[11] = IupSetAtt( "dlg", IupDialog(
    IupSetAtt( NULL, IupVbox(
      IupHbox(
        IupSetAtt( NULL, IupFrame(
          IupVbox(
            IupHbox(
              IupLabel( "Type" ),
              named[2] /* comm_type */,
            NULL),
            IupHbox(
              IupLabel( "Port" ),
              named[3] /* comm_port */,
            NULL),
            IupHbox(
              IupLabel( "HDLC address" ),
              named[4] /* phy_address */,
            NULL),
            IupHbox(
              IupLabel( "User" ),
              named[5] /* user */,
            NULL),
            IupHbox(
              IupLabel( "Authentication" ),
              named[6] /* auth */,
            NULL),
            IupHbox(
              IupLabel( "Password" ),
              named[7] /* password */,
            NULL),
            named[8] /* highspeed */,
            IupFill(),
          NULL)
        ), 
          "TITLE", "Communication parameters", NULL ),
        IupSetAtt( NULL, IupFrame(
          IupVbox(
            IupSetAtt( NULL, IupMultiLine( "myaction" ), 
              "SIZE", "200x40", 
              "EXPAND", "YES", 
              "VALUE", "", NULL ),
          NULL)
        ), 
          "TITLE", "Output logs", NULL ),
      NULL),
      IupHbox(
        named[1] /* progress */,
        named[9] /* button_start */,
      NULL),
      named[10] /* button_exit */,
    NULL), 
      "GAP", "5", 
      "ALIGNMENT", "ARIGHT", 
      "MARGIN", "2x2", NULL )
  ), 
    "TITLE", "DLMS/Cosem firmware upgrade", 
    "MENU", "mnu", NULL );
}
